### ISSUE TITLE
sub folder components  nuxt

### ISSUE THREAD

**Issue by reslear** [yungsilva/named-exports#2]
i have, a problem
____
i am using Nuxt: `nuxt.config.js`

```javascript
const NamedExports = require('named-exports')
...
build: {
  plugins: [
    new NamedExports({ path: 'components' })
  ],
}
```

on components (): 
```javascript
import {header} from '@/components/';
```
____

plugin create `index.js` files in all subfolders (ex `/component/layouts/header.vue `create in this path `index.js` but not in root `/components/index.js`)

not comfortable:
```javascript
import {header} from '@/components/header';
import {sideleft} from '@/components/layers/all';
```
I would like to:
```javascript
import {header, sideleft} from '@/components';
```

To use only the root file and disable generation in subfolders?

**Comment by yungsilva** [comment]
Hello @reslear 

Try this in `nuxt.config.js`

import namedExports from 'named-exports'

```
build: {
  plugins: [
    new namedExports({
        path: 'components',
        recursive: false
    })
  ],
}
```
